#Compilar con: make
#Ejecutar con: make run
#Limpiar con: make clean

CC = g++
CFLAGS = -g -std=c++17

p5_Sorting: main.cc
	$(CC) $(CFLAGS) -o p5_Sorting main.cc

p5_Mod: mod.cc
	$(CC) $(CFLAGS) -o p5_Mod mod.cc
	
clean:
	rm -f *.o p5_Mod
	rm -f *.o p5_Sorting